sudo: required
services:
  - docker

before_install:
  - docker build -t neeraj33negi/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true neeraj33negi/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-035229085366"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key: "$AWS_SECRET_KEY"
